#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
#+Title: Applied Economic Analysis
#+Author: Jan Boone
#+OPTIONS: toc:2 timestamp:nil toc:nil todo:nil
#+EXPORT_EXCLUDE_TAGS: noexport

This website contains the material for the MSc course Applied Economics.

**This website is under construction for 2021/2022**

This year the course is taught by:
+ Jan Boone
+ Sjak Smulders
+ Barbora Písecká


* Python track AEA
  :PROPERTIES:
  :CUSTOM_ID:       python_track_AEA
  :END:

For this course we use the following resources:

+ Jean Tirole, [[https://press.princeton.edu/titles/10919.html][Economics for the Common Good]],
+ for students following the python track in this course: We are very happy that we partner with [[https://www.datacamp.com/][datacamp]] for this course to teach you python. [[https://www.datacamp.com/about][Datacamp]] offers great on-line courses for you to learn python.

#+TOC: headlines 2


* Screencasts
  :PROPERTIES:
  :CUSTOM_ID:       screencasts_AEA
  :END:

For this course a series of screencasts is available. The screencasts can be found on this [[file:./pagescreencasts.org][webpage.]]


* Organisation of the course

Since we have recorded screencasts, we will not repeat these during the lectures. The lectures are meant for interaction (only).

** For the python track, we will use the following format:

+ in the lectures we will answer questions that you ask us
+ in order to prepare these answers, it is useful if you create an issue via [[https://github.com/janboone/applied-economics/issues][this link]]
  + using the link, create an "issue" where you explain what your question is: what did you try and why did it not work?
    + hence not a something like "I do not know the answer to: *Question* Calculate the total welfare that this planner can achieve. Denote this value ~max_welfare~."
    + but "I tried to calculate total welfare in the following way ... but then I get the following error ..."
    + describing your question like this, helps you better understand what your problem is
    + and it helps us to answer the question in class.
+ for us to be able to prepare these answers, submit the issue on the Friday before the week in which we discuss the topic
  + hence, finish the sections in the week before they are discussed in class
  + if you can solve everything yourself, there is no need to attend the lecture (but you are, of course, welcome to do so)
  + this is one of the advantages of programming: you can see for yourself whether it works or not.

A suggested workflow for the python track is:
+ follow the Datacamp courses and make notes of what you learn at Datacamp in a notebook on the jupyterlab server
  + in this way it is easy to refer back to useful code snippets that you see on Datacamp
+ go through the notebook and try to answer the questions and assignments
+ if you get stuck with a problem, watch the corresponding screencast for this part. It gives hints and ways to solve the problems
+ if you still cannot figure it out, create an issue on github to ask us
+ we will answer your questions in class

Hence, sitting back and hoping to copy all answers during the lectures is not going to work. This is a bad strategy anyway: you learn python by trying (and failing) to code; not by copy/paste-ing the correct code.

** For the canon track, we will use the following format:

Over the semester, you write – in a team – a “canon” in which you collect and explain insights from economics on a particular societal problem (e.g. Housing crisis, Pandemics).

To guide you in this work, the course teaches you how to “see economics everywhere” and communicate insights from economics to non-economists. You develop your skills and build up all the elements of the canon through:

+ reading the book by Tirole, Economics for the common good https://press.princeton.edu/books/hardcover/9780691175164/economics-for-the-common-good,
+ making assignments,
+ actively participating in our classes.
+ In the lectures we will:
  + have group discussions
  + develop material and practice economic analysis for your canon assignment
  + answer questions about the course resources (book and video material)
  + discuss progress and answer questions about assignments (proto-canon and canon)

A suggested workflow for the canon track is:

+ to prepare for lecture: read the Tirole book chapters associated to the upcoming lecture
+ attend lecture on campus and participate,
+ do the assignment within one week after the lecture.
+ if needed, send a question or material to j.a.smulders@uvt.nl
+ to get grades (protocanon assignment S1 and final canon) and to get feedback (assignment S2-7), stick to deadlines


** Lecture schedule
   :PROPERTIES:
   :CUSTOM_ID:       lecture_schedule_AEA
   :END:

At the moment, it is not clear whether the lectures will be live/online or hybrid. We have rooms booked for all lectures, so hopefully we can do things live in the classroom. But during the semester corona restrictions may force us to teach online.

If we will teach online, we use zoom and the links and passwords for these lectures will be published on Canvas.

Please keep an eye on the Canvas page where we will keep you posted on whether a lecture will be on campus or online.

| week | day |       date |        time | Staff       | room            | Topic                                                                     | Tirole   | Datacamp           |
|------+-----+------------+-------------+-------------+-----------------+---------------------------------------------------------------------------+----------+--------------------|
|   35 | Tue | 2021-08-31 | 14:45-16:30 | Smulders*   | CZ 120 (hybrid) | Canon 0: intro                                                            |          |                    |
|   35 | Fri | 2021-09-03 | 14:45-16:30 | Boone*      | zoom (only)     | Intro python, markdown, github, jupyterlab                                |          |                    |
|   36 | Fri | 2021-09-10 | 14:45-16:30 | Smulders    | DZ 2            | Canon 1: The economist                                                    | 1,2,3,4  | Intro (1,2)        |
|   37 | Tue | 2021-09-14 | 12:45-14:30 | Ladenstein* | MDZ 20          | Plenary Career Session                                                    |          | Intro (3)          |
|   37 | Fri | 2021-09-17 | 14:45-16:30 | Smulders    | DZ 2            | Canon 2: Jobs                                                             | 6,7,9    | Intro (4)          |
|   38 | Mon | 2021-09-20 | 13:45-17:30 | *           | RTZ 202         | Career Orientation & Preparation - Personal Branding & Networking         |          | Intermediate (1,2) |
|   38 | Mon | 2021-09-20 | 13:45-17:30 | *           | RTZ 501         | Career Orientation & Preparation - Personal Branding & Networking         |          |                    |
|   38 | Mon | 2021-09-20 | 13:45-17:30 | *           | RTZ 103         | Career Orientation & Preparation - How to prepare for Assessments         |          |                    |
|   38 | Fri | 2021-09-24 | 13:45-17:30 | *           | RTZ 102         | Career Orientation & Preparation - How to prepare for Assessments         |          |                    |
|   38 | Fri | 2021-09-24 | 13:45-17:30 | *           | RTZ 303         | Career Orientation & Preparation - Talent Management                      |          |                    |
|   38 | Fri | 2021-09-24 | 13:45-17:30 | *           | RTZ 202         | Career Orientation & Preparation - LinkedIn & Networking through LinkedIn |          | Intermediate (3,4) |
|   40 | Fri | 2021-10-08 | 14:45-16:30 | Boone       | DZ 1            | Q&A python/Datacamp                                                       |          | Intermediate (5)   |
|   41 | Fri | 2021-10-15 | 14:45-16:30 | Smulders    | DZ 2            | Canon 3: Climate                                                          | 8,16     | Pandas (1,2)       |
|   45 | Fri | 2021-11-12 | 14:45-16:30 | Smulders    | DZ 2            | Canon 4: Finance                                                          | 10,11,12 | Pandas (3,4)       |
|   46 | Wed | 2021-11-17 | 16:45-18:30 | Boone       | CZ 121          | The market                                                                |          |                    |
|   46 | Fri | 2021-11-19 | 14:45-16:30 | Boone       | DZ 1            | Asymmetric information                                                    |          |                    |
|   47 | Fri | 2021-11-26 | 14:45-16:30 | Smulders    | DZ 2            | Canon 5: regulation                                                       | 13,17    |                    |
|   48 | Wed | 2021-12-01 | 16:45-18:30 | Boone       | CZ 121          | Financial crisis                                                          |          |                    |
|   48 | Fri | 2021-12-03 | 14:45-16:30 | Boone       | DZ 1            | Empirical research                                                        |          |                    |
|   49 | Wed | 2021-12-08 | 16:45-18:30 | Boone       | CZ 121          | Health care regulation                                                    |          |                    |
|   49 | Fri | 2021-12-10 | 14:45-16:30 | Smulders    | DZ 2            | Canon 6: Behavior                                                         | 5,15     |                    |

"*" indicates that everyone has to attend this lecture (irrespective of whether you do the canon or python track).

** First Python Lecture

[[file:./Introduction_Lecture.org::#introduction][Introduction Lecture]]

*** Assignment 1
    :PROPERTIES:
    :CUSTOM_ID:       assignment_1_AEA
    :END:

Do the following four steps:
+ create a github account on [[https://github.com/][github]] (you need this for the next step)
+ fill in this [[https://forms.gle/bUS3sZZYgM4y1wdJ7][google form]] before **Friday September 17, 2021**
  + note that you need to login on google with your TiU credentials when you fill in the form
  + e.g. make sure that your browser is not logged in with your gmail-address
  + if necessary, create an incognito/private window
+ go to
  + [[https://jupyterlab.uvt.nl/][jupyter lab]]
    + IT suggests that you use the Firefox browser to access jupyter lab
    + sometimes it helps to access jupyter lab with an incognito/private window
  + or --if all else fails-- you can use [[https://colab.research.google.com/][google's colab]]
+ create a new python notebook and type the following code in the first cell:
#+BEGIN_SRC ipython
%%bash

git clone https://github.com/janboone/applied-economics
#+END_SRC
+ then press the Shift key and Enter key at the same time
+ this creates a folder on the server `applied-economics` that contains the material for the python part of the course.
+ Note: you can only run this command once. If you run it again, you get an error since the folder already exists.

*** Final assignment

+ instructions for the final assignment can be found below.

** Datacamp

You can get access to Datacamp via the [[https://www.tilburguniversity.edu/students/skills/programming][university website]].

From Datacamp, do the following courses:

+ Intro: [[https://www.datacamp.com/courses/intro-to-python-for-data-science]]
+ Intermediate: [[https://www.datacamp.com/courses/intermediate-python-for-data-science]]
+ Pandas: https://learn.datacamp.com/courses/data-manipulation-with-pandas

It is up to you how to combine the Datacamp courses with the [[file:./pagescreencasts.org][Screencasts]]. We suggest to finish the Datacamp Intro course first. As there is no economics on Datacamp, some students prefer to start with the screencasts after the Intro. Others prefer to finish all the Datacamp courses before they start on the screencasts, so that they have seen all the python and pandas material.

** Deadlines
   :PROPERTIES:
   :CUSTOM_ID: deadlines_AEA
   :END:

We recommend that you finish the Intermediate course before October 10, 2021 and the Pandas course before November 12, 2021.

The deadline for the *final python assignment* is: Friday January 28th, 2022. However, if you need your grade before the end of January, you need to submit your final assignment by Friday January 14th, 2022. Let us know by email that your assignment needs to be graded early.

If you do the python track in this course, your grade is determined by the final assignment (only).

The resit deadline for the python assignment is: Friday August 26th, 2022. Let us know by email that you have submitted your assignment for the resit. Further, follow the instructions below on how to submit an assignment on github and fill in the google form etc.

** Questions

 If you have questions/comments about this course, go to the [[https://github.com/janboone/applied-economics/issues][issues page]]
 open a new issue (with the green "New issue" button) and type your
 question. Use a title that is informative (e.g. not "question", but
 "question about the second assignment"). Go to the next box ("Leave a comment")
 and type your question. Then click on "Submit new issue". We will
 answer your question as quickly as possible.

 The advantages of the issue page include:

 + if you have a question, other students may have it as well; in this
   way we answer the questions in a way that everyone can see it. Also
   before asking the question, you may want to check whether it was
   asked/answered before on the issue page
 + we answer your question more quickly than when you email us
 + you increase your knowledge of github!

 Only when you need to include privately sensitive information ("my cat
 has passed away"), you can send an email.

 In order to post issues, you need to create a github account (which
 you need anyway to follow this course).

 Note that if your question is related to another issue, you can react
 to the earlier issue and leave a comment in that "conversation".



* Final Assignment
  :PROPERTIES:
  :CUSTOM_ID: final_assignment_AEA
  :END:

+ The python assignment you can do alone or with at max. one other student (i.e. max group size is 2).
+ for the deadline of the python assignment, see [[Deadlines]] above
+ on Canvas we give you the link to the github repos. with the ~assignment_template.ipynb~
+ once you have "cloned" the applied-economics repository, you can see there the ~assignment_template.ipynb~ notebook. This gives you an idea of the template for the final assignment
+ to submit your final assignment:
  + do not change the name of the ~assignment_template.ipynb~ notebook
  + fill in this [[https://forms.gle/QQxvEwYWAUwbZLBp9][google form]]
  + push the final notebook on the github classroom repository


** TODO Instructions for submitting final assignment to be put on Canvas :noexport:

- [ ] create assignment on github classroom with the AEA/datascience template/notebook: https://github.com/janboone/AEA_final_assignment or https://github.com/janboone/datascience_assignment_template
- [ ] create google form for students to fill in once they finish assignment: replace last year link above
- [ ] change link to the classroom assignment below

- attach instructions: [[file:~/Google Drive/repositories/github/websites/github_classroom_assignments/how_to_use_nbgrader_github_classroom/Manual_students.pdf]]
- create and post screencast where notebook is downloaded and uploaded on github
- show previous step during lecture


Dear students,

The link for the final AEA python assignment (template) is: https://classroom.github.com/a/hIBtWC9c (this is the link for 2021/2022)

You can do the assignment on your own or with (at max.) one other student. When you use the link to the assignment, you will be asked for your team's name. Choose your favorite name!

When you finish your assignment:

1. download your assignment (jupyter notebook) from jupyter lab (or google colabs; or check where it is on your computer when using anaconda) to your computer (e.g. in the folder Downloads)

2. push it onto your assignment's github repository

3. fill in the google form where the link to the form is on the website: https://janboone.github.io/applied-economics/index.html#final_assignment_AEA

We need the information from the google form to link your assignment to your student number which is needed for the exam administration.

If you have questions about the assignment or the procedure described above, create an issue on the webpage at: https://github.com/janboone/applied-economics/issues

Then you can see whether other students had the same question (which was already answered) or fellow-students can learn from your question. These issues can be read by anyone, so do not provide any privacy related information.

Good luck with the assignment,

Jan.

** what we are looking for

The idea of the assignment is that you report your findings in a transparent way that can easily be verified/reproduced by others. The intended audience is your fellow students. They should be able to understand the code you write together with the explanations that you give for this code.

The following ingredients will be important when we evaluate your assignment:

+ Start with a clear and transparent *question*.
+ There are a lot of interesting economic questions for which you do not need programming to find the answer. However, as an important part of this course is programming in python, we want to see some programming. So choose a question where you can show off your programming skills!
+ Briefly *motivate* why this question is interesting.
+ Explain the *method* or data that you use to answer the question.
+ Give the *answer* that you find (as a preview).
+ Mention the main *assumptions* that you need to get this answer.
+ When you use information, create a link to this information. The reader then only needs to click to find the relevant information.
+ If you use data, present graphs of the data.
+ Include the data in your github respository so that we can replicate your analysis.
+ If you use equations, use latex to make them easy to read.
+ Explain your code, the reader --think of your fellow students-- must be able to easily follow what you are doing.
+ Present a clear conclusion/answer to your question.
+ Programming is great to do *sensitivity analysis*, just do the same you did before, but now with different parameter values.
+ Include some *discussion* of what you find and elements on which you need additional information.

Two remarks:
+ you can copy code from the web; but
  + make sure that you explain the code that you use so that another student of the course understands it and can use it;
  + give the reference of the code that you copy;
+ use *common sense*: it is not always necessary to have a full blown economic model, but we do expect you to think!
  + in the past we had students looking at the effect of age on income in sports; "theory" suggests that this relation is hump-shaped: 5 year olds and 80 year olds tend not to earn a lot of money as elite athletes; the students presented a scatter plot with a clear hump-shape; then they wrote "now we do a linear regression". For each step that you program, ask yourself why this step makes sense and then explain this in your notebook.


** resit of final assignment

The resit of the final assignment needs to be a new project compared to the one you handed in before. The easiest way to achieve this is to choose a new research question; if you are using data, choose a new data set. Simply adjusting your first submission based on our feedback will be not be enough.

Simply adjusting your first submission based on our feedback will be not be enough. 

Otherwise, follow the procedure above on how to submit the assignment and fill in the google form.


** examples of assignments from previous years

+ [[https://joelleduff.github.io/Final/STindex.html][first example]]
+ [[https://joostbouten.github.io/AEA_Joost_Twan.html][second example]]
+ [[https://github.com/koenbosch/Assignments/blob/master/KOEN%20VAN%20DEN%20BOSCH%20MARTIJN%20BLOEMBERG%20PYTHON%20ASSIGNMENT%20AEA1.ipynb][third example]]
+ [[https://github.com/RoelSchoen/assignments][fourth example]]
+ [[https://colab.research.google.com/github/aetknaapen/assignments/blob/master/Python_assignment_final.ipynb][fifth example]]

* Python as programming language

We use python as programming language. I guess, a fair question is:
why python? The non-scientific answer is: because I like it a lot.

Other answers, better motivated than my own, include:

- https://www.datacamp.com/community/blog/python-scientific-computing-case
- https://developer.ibm.com/blogs/use-python-for-scientific-research/
- google the question if you want more answers.

We will program python using the jupyter notebook. One motivation to use the jupyter notebook is based on a paper in the AER:

[[yt:oP9Qcjq8UVI]]

Note that this is a presentation on a python conference having nothing to do with economics. The fact that this presentation uses an AER paper to motivate using the notebook, may induce a wee pause in which you ponder the state of our discipline.

After this pause, take a look at some notebooks:

[[https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks]]


Links and resources for python:

+ [[https://scipy-lectures.github.io/]]
+ [[http://www.physics.nyu.edu/pine/pymanual/html/pymanMaster.html]]
+ https://aeturrell.github.io/coding-for-economists/intro.html (introduction to python with economics in mind)
+ https://python.quantecon.org/intro.html (fairly advanced economics with python)
+ [[https://www.youtube.com/playlist?list=PLi01XoE8jYohWFPpC17Z-wWhPOSuh8Er-]] (video lectures on a number of python topics)

** Jupyter notebooks


*** Markdown

For the assignment it is useful to know a bit of markdown. You can
either google "markdown tutorial" or use one of the following websites:

+ [[http://daringfireball.net/projects/markdown/]]
+ [[https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet]]

*** Latex

For the python assignment it is useful to familiarize yourself with
latex. Note that you do not need to type a whole document in latex (so
don't worry about preambles etc.), you just need to know how to type
$x^2$, $\alpha,\beta$ or have math displayed like

\begin{equation}
a^2 + b^2 = c^2
\end{equation}

Google "latex tutorial" or go to pages like:

+ [[http://users.dickinson.edu/~richesod/latex/latexcheatsheet.pdf]]
+ [[https://www.latex-tutorial.com/tutorials/amsmath/]]
+ [[http://www.andy-roberts.net/writing/latex/mathematics_1]]

and focus on typesetting.
